services:
  - type: web
    name: voice-collectes
    env: node
    buildCommand: |
      npm install
      node scripts/post-deploy.js
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_IMPORT
        value: "true"
      - key: DB_HOST
        fromDatabase:
          name: voice-collectes-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: voice-collectes-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: voice-collectes-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: voice-collectes-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: voice-collectes-db
          property: database
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /check-config

databases:
  - name: voice-collectes-db
    databaseName: voice_collectes
    user: root
    plan: free 