services:
  - type: web
    name: voice-collecte-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: voice-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: ton_cloud_name
      - key: CLOUDINARY_API_KEY
        value: ta_api_key
      - key: CLOUDINARY_API_SECRET
        value: ton_api_secret

databases:
  - name: voice-db
    databaseName: voice_db
    user: voice_user
